# Generated by Django 4.0.6 on 2022-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='日付')),
                ('place', models.CharField(max_length=20, verbose_name='PLACE')),
                ('genre', models.CharField(max_length=40, verbose_name='GENRE')),
                ('accompany', models.CharField(max_length=10, verbose_name='PEOPLE')),
                ('text', models.TextField(verbose_name='メモ')),
            ],
            options={
                'verbose_name_plural': 'Tabi_data',
            },
        ),
    ]
