# Generated by Django 4.0.6 on 2022-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabi',
            options={'verbose_name_plural': 'Tabi_data'},
        ),
        migrations.AddField(
            model_name='tabi',
            name='accompany',
            field=models.CharField(default='', max_length=10, verbose_name='PEOPLE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabi',
            name='genre',
            field=models.CharField(default='', max_length=40, verbose_name='GENRE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabi',
            name='place',
            field=models.CharField(default='', max_length=20, verbose_name='PLACE'),
            preserve_default=False,
        ),
    ]
