# Generated by Django 4.0.6 on 2022-08-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_alter_tabi_accompany_alter_tabi_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabi',
            name='genre',
            field=models.CharField(choices=[('1', '体験／教室'), ('2', 'スポーツ／観戦'), ('3', '自然／景色／花'), ('4', '動物'), ('5', '宿泊'), ('6', 'グルメ'), ('7', '文化／芸術'), ('8', '祭り'), ('9', 'テーマパーク'), ('10', 'ショッピング'), ('11', '世界遺産／遺産'), ('12', '乗り物'), ('13', 'スパ／エステ／温泉'), ('14', '学習／研修'), ('15', 'その他')], max_length=40, verbose_name='ジャンル'),
        ),
    ]
