# Generated by Django 4.0.6 on 2022-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_alter_tabi_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabi',
            name='accompany',
            field=models.CharField(choices=[('A', '単独'), ('B', '友人'), ('C', '恋人'), ('D', '家族'), ('E', '仕事関係者'), ('F', '趣味仲間'), ('G', 'その他')], max_length=10, verbose_name='同行者'),
        ),
    ]
